export const projects = [
    { id: 141640, abbreviation: "По проекту", fullName: "По проекту" },
    { id: 141641, abbreviation: "Объекты", fullName: "Объекты" },
    { id: 141642, abbreviation: "РД", fullName: "Рабочая документация" },
    { id: 141643, abbreviation: "МТО", fullName: "Материально-техническое обеспечение" },
    { id: 141644, abbreviation: "СМР", fullName: "Строительно-монтажные работы" },
    { id: 141645, abbreviation: "График", fullName: "График выполнения работ" },
    { id: 141646, abbreviation: "МиМ", fullName: "Механизмы и материалы" },
    { id: 141647, abbreviation: "Рабочие", fullName: "Рабочие ресурсы" },
    { id: 141648, abbreviation: "Капвложения", fullName: "Капитальные вложения" },
    { id: 141649, abbreviation: "Бюджет", fullName: "Бюджет проекта" },
    { id: 141650, abbreviation: "Финансирование", fullName: "Финансирование проекта" },
    { id: 141651, abbreviation: "Панорамы", fullName: "Панорамы объектов" },
    { id: 141652, abbreviation: "Камеры", fullName: "Камеры видеонаблюдения" },
    { id: 141653, abbreviation: "Поручения", fullName: "Поручения и задачи" },
    { id: 141654, abbreviation: "Контрагенты", fullName: "Контрагенты и партнёры"}, ]